---
- name: start
  hosts: localhost
  gather_facts: true

- name: install package
  hosts: localhost
  become: yes
  gather_facts: false
  roles:
    - install-packages
    - install-docker
    - install-chrome
    - install-vscode
