---
- name: install apt packages
  become: True
  apt: pkg={{ item }} update_cache=yes cache_valid_time=3600
  with_items:
    - git
    - tmux
    - tree
    - vagrant
    - vim
    - virtualbox
    - wget
