---
- name: "Does the Vscode apt file exist?"
  stat:
    path: "/etc/apt/sources.list.d/vscode.list"
  register: vscode_apt_list

- name: "Add Vscode key"
  become: True
  apt_key:
    url: 'https://packages.microsoft.com/keys/microsoft.asc'
    state: present
  when: not vscode_apt_list.stat.exists

- name: "Install Vscode repo"
  become: True
  apt_repository:
    repo: 'deb [arch=amd64] https://packages.microsoft.com/repos/code stable main'
  when: not vscode_apt_list.stat.exists

- name: "Install desktop application"
  become: True
  apt:
    name:
      - code
    state: latest

- name: delete apt file
  become: True
  file:
    path: /etc/apt/sources.list.d/vscode.list
    state: absent
